var Data = Data || {};

Data.Sets = [
  {
    id:         1,
    artistId:   1,
    venueId:    1,
    type:       'set',
    name:       'Bondax',
    artist:     'Bondax',
    venue:      'Pitchfork Music Festival',
    background: 'bondax.jpg',
    thumbnail:  'bondax-thumb.jpg',
    videoId:    'thdEvA0KHiM',
    genre:      'Techno',
    date:       '12.12.2014',
    tracks: [
      { title: 'Lorem', artist: 'Ipsum', startsAt: 0,    length: 300, link: 'http://google.com' },
      { title: 'Dolor', artist: 'Sit',   startsAt: 100,   length: 300, link: 'http://google.com' },
      { title: 'Lorem', artist: 'Ipsum', startsAt: 250,   length: 300, link: 'http://google.com' },
      { title: 'Dolor', artist: 'Sit',   startsAt: 400,   length: 300, link: 'http://google.com' },
      { title: 'Lorem', artist: 'Ipsum', startsAt: 800,   length: 300, link: 'http://google.com' },
      { title: 'Dolor', artist: 'Sit',   startsAt: 1200,   length: 300, link: 'http://google.com' },
      { title: 'Lorem', artist: 'Ipsum', startsAt: 1300,   length: 300, link: 'http://google.com' },
      { title: 'Dolor', artist: 'Sit',   startsAt: 2000,   length: 300, link: 'http://google.com' }
    ]
  },
  {
    id: 2,
    artistId: 2,
    venueId: 2,
    type: 'set',
    name: 'Panacea',
    artist: 'Panacea',
    venue: 'The World of Drum & Bass',
    background: 'panacea.jpg',
    thumbnail: 'panacea-thumb.jpg',
    videoId: 'asPP5s1R0bo',
    genre: 'Drum & Bass',
    date: '13.9.2014',
    tracks: [
        { title: 'Intro', artist: '', startsAt: 0, length: 60, link: ''},
        { title: 'The Panacea', artist: 'Pendulum Spoof', startsAt: 60, length: 666, link: 'http://google.com/' },
        { title: 'Prolix & Misanthrop', artist: 'Transcendence', startsAt: 120, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea', artist: 'Cryptonomicon (C.A.2K. Remix)', startsAt: 180, length: 666, link: 'http://google.com/' },
        { title: 'Counterstrike & Hallucinator', artist: 'Revolver', startsAt: 240, length: 666, link: 'http://google.com/' },
        { title: 'Looh', artist: 'Partylooh', startsAt: 300, length: 666, link: 'http://google.com/' },
        { title: 'Teddy Killerz', artist: 'Jackyl & Hyde', startsAt: 360, length: 666, link: 'http://google.com/' },
        { title: 'I Am Legion', artist: 'Make Those Moves (Teddy Killerz Remix)', startsAt: 420, length: 666, link: 'http://google.com/' },
        { title: 'Rusty K', artist: 'AC 130', startsAt: 480, length: 666, link: 'http://google.com/' },
        { title: 'Mustard Pimp', artist: 'Renegade (SPL Remix)', startsAt: 540, length: 666, link: 'http://google.com/' },
        { title: 'Freqax & Sinister Souls', artist: 'Burn It', startsAt: 600, length: 666, link: 'http://google.com/' },
        { title: 'Tech Itch', artist: 'Demon', startsAt: 660, length: 666, link: 'http://google.com/' },
        { title: 'SPL & Eye-D', artist: 'Pyramid Punk', startsAt: 720, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea & C.A.2K.', artist: 'Tensions Are High', startsAt: 780, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea', artist: 'VD Majick (Counterstrike Remix)', startsAt: 840, length: 666, link: 'http://google.com/' },
        { title: 'Mefjus & Emperor', artist: 'Void Main Void', startsAt: 900, length: 666, link: 'http://google.com/' },
        { title: 'Jade', artist: 'What You Are', startsAt: 960, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea', artist: 'Jungle Jupiter', startsAt: 1020, length: 666, link: 'http://google.com/' },
        { title: 'Ewun', artist: 'Kop Killa', startsAt: 1080, length: 666, link: 'http://google.com/' },
        { title: 'Mindscape', artist: 'Brightness', startsAt: 1140, length: 666, link: 'http://google.com/' },
        { title: 'CVPELLV', artist: 'Irak', startsAt: 1200, length: 666, link: 'http://google.com/' },
        { title: 'The Prototypes', artist: 'Just Bounce', startsAt: 1260, length: 666, link: 'http://google.com/' },
        { title: 'DJ Fresh', artist: 'Signal', startsAt: 1320, length: 666, link: 'http://google.com/' },
        { title: 'Joe Ford', artist: 'The Moment Feat. Tash Baxter', startsAt: 1380, length: 666, link: 'http://google.com/' },
        { title: 'Hallucinator', artist: 'Extinction', startsAt: 1440, length: 666, link: 'http://google.com/' },
        { title: 'Goldberg Variations, Gancher & Ruin', artist: 'Dirty Hand Of Gandolf', startsAt: 1480, length: 666, link: 'http://google.com/' },
        { title: 'Gridlok', artist: 'Hooked (Tech Itch & Dieselboy Remix)', startsAt: 1540, length: 666, link: 'http://google.com/' },
        { title: 'Current Value & Coresplittaz Feat. Snow', artist: 'Dispelling Fear (The Panacea VIP)', startsAt: 1600, length: 666, link: 'http://google.com/' },
        { title: 'Audio', artist: 'Wildfire', startsAt: 1660, length: 666, link: 'http://google.com/' },
        { title: 'Enei', artist: 'Prometheus', startsAt: 1720, length: 666, link: 'http://google.com/' },
        { title: 'Limewax', artist: 'Icicle', startsAt: 1780, length: 666, link: 'http://google.com/' },
        { title: 'Dose', artist: 'Haphazard', startsAt: 1840, length: 666, link: 'http://google.com/' },
        { title: 'State Of Mind', artist: 'No Operative', startsAt: 1900, length: 666, link: 'http://google.com/' },
        { title: 'Noisia', artist: 'Shaking Hands', startsAt: 1960, length: 666, link: 'http://google.com/' },
        { title: 'Current Value', artist: 'Triple', startsAt: 2020, length: 666, link: 'http://google.com/' },
        { title: 'Goldberg Variations, Gancher & Ruin', artist: 'Nie Of Kreuzucht (VIP)', startsAt: 2080, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea', artist: 'Gravity Revolver', startsAt: 2140, length: 666, link: 'http://google.com/' },
        { title: 'C.A.2K.', artist: 'Sad', startsAt: 2200, length: 666, link: 'http://google.com/' },
        { title: 'C.A.2K.', artist: 'Power Punch', startsAt: 2260, length: 666, link: 'http://google.com/' },
        { title: 'High Rankin', artist: 'Horrorcane (The Panacea Ultra-epic VIP)', startsAt: 2320, length: 666, link: 'http://google.com/' },
        { title: 'The Panacea Feat. Goldberg Variations & Untergang Berlin', artist: 'Ryse & Shiiine﻿', startsAt: 2380, length: 666, link: 'http://google.com/' }
    ]
  }
];